In [33]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype=np.float32)
print(a)

[1. 2. 3.]


In [3]:
c = np.array([[1, 2+2j, 3], [4, 5, 6]]) #dtype = complex
print(c)

[[1.+0.j 2.+2.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1. 2. 3.]
[100.   2.   3.]
[1. 2. 3.]


In [8]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.shape)

(12,)


In [9]:
b= a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
b = a.reshape(2,2,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
for i in b:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
for row in b:
    for ele in row:
        print(ele)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [13]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
c = np.array([0,3,4,9])
d = np.sin(c)
d

array([ 0.        ,  0.14112001, -0.7568025 ,  0.41211849])

In [16]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2,0],
              [3,4]])
A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [17]:
A @ B #matrix product

array([[5, 4],
       [3, 4]])

In [18]:
A.dot(B) #matrix product (frequently use)

array([[5, 4],
       [3, 4]])

In [19]:
rg = np.random.default_rng(1) #Fixed random array
b = rg.random((2,3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [20]:
a = np.ones(3, dtype = np.int32)
b = np.linspace(0, np.pi, 3)
b

array([0.        , 1.57079633, 3.14159265])

In [21]:
rd = np.random.rand(2,3)
rd

array([[0.04332884, 0.83491135, 0.53046395],
       [0.55050709, 0.08821525, 0.69402881]])

In [22]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [23]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [24]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [25]:
a[::-1] #Reverse a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [26]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [27]:
print(a.T) #Tranpose matrix
print(a.T.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [28]:
a.resize(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
a.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
a = np.floor(10 * rg.random((2,2)))
print(a)
b = np.floor(10 * rg.random((2,2)))
print(b)

[[8. 4.]
 [5. 0.]]
[[7. 5.]
 [3. 7.]]


In [31]:
np.vstack((a,b))

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.]])

In [32]:
np.hstack((a,b))

array([[8., 4., 7., 5.],
       [5., 0., 3., 7.]])